### ISSUE TITLE
How do I specify the return result's language

### ISSUE THREAD

**Issue by ghost** [mikedemers/rbing#2]
Dear Sir:
       I use your rbing api, and I want to know  how do I specify the return result's language. I check the code, and try add "language:en" but it seems not work. I want to know if there is any way to specify the return result's language.  Many 
thanks.

Yours sincerely

**Comment by mikedemers** [comment]
The Bing API has a "Market" option on web search requests: http://msdn.microsoft.com/en-us/library/dd251064.aspx

For example, you can get French results for "food" with something like:

```
    bing.web("food", :Market => "fr-FR")
```

**Comment by ghost** [comment]
Thanks for your kindly help. I also tried :language => "en, it also works, thanks :)
