### ISSUE TITLE
rbing needs to be updated to support the new Bing API

### ISSUE THREAD

**Issue by sdball** [mikedemers/rbing#8]
From their [migration doc](http://www.bing.com/webmaster/content/developers/ADM_MIGRATION_GUIDE.docx), here are the changes that need to happen.
- query url needs to change to https://api.datamarket.azure.com/Bing/Search/
- and rbing could potentially support the new "web only" endpoint: https://api.datamarket.azure.com/Bing/SearchWeb/
- the requested source (e.g. Web) needs to be appended to the endpoint
- the query needs to be converted to a urlencoded string on the URL
  - e.g. https://api.datamarket.azure.com/Bing/Search/Web?Query=%27Ruby%27
  - a full query with format: https://api.datamarket.azure.com/Bing/Search/Web?Query='Ruby'&$top=10&$skip=20&$format=json
- the full URI needs to be accessed with basic auth. Username is ignored (at one point in the docs they say just leave it blank, in a couple examples they use account key) and password is the new Bing API Account Key.

**Comment by travisp** [comment]
@sdball, There are a couple forks around to deal with this as I suspect this project has been abandoned.

This one is based on the "web only" endpoint:

https://github.com/KellyMahan/rbing/tree/azure

And I just created one based on that fork, but which instead uses the regular search api and so allows non-web searches:

https://github.com/travisp/rbing/tree/features/azure

Hope this helps you and others who come across it.

**Comment by sdball** [comment]
@travisp Thanks for the heads up on those projects. I ended up just coding my own interface to the Bing web results for the time being, but was hoping that gem would be updated.

How about a pull request of the update back to here?

**Comment by mnort9** [comment]
+1
